
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class SendMailTask
{

    private SendMailTaskAttachments attachmentsField;

    private string nameField;

    private string sMTPServerField;

    private string fromField;

    private string toField;

    private string ccField;

    private string bCCField;

    private string subjectField;

    private string priorityField;

    private string messageSourceTypeField;

    private string messageSourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachments", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SendMailTaskAttachments Attachments
    {
        get
        {
            return this.attachmentsField;
        }
        set
        {
            this.attachmentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SMTPServer
    {
        get
        {
            return this.sMTPServerField;
        }
        set
        {
            this.sMTPServerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string From
    {
        get
        {
            return this.fromField;
        }
        set
        {
            this.fromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string To
    {
        get
        {
            return this.toField;
        }
        set
        {
            this.toField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CC
    {
        get
        {
            return this.ccField;
        }
        set
        {
            this.ccField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BCC
    {
        get
        {
            return this.bCCField;
        }
        set
        {
            this.bCCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Subject
    {
        get
        {
            return this.subjectField;
        }
        set
        {
            this.subjectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MessageSourceType
    {
        get
        {
            return this.messageSourceTypeField;
        }
        set
        {
            this.messageSourceTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MessageSource
    {
        get
        {
            return this.messageSourceField;
        }
        set
        {
            this.messageSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SendMailTaskAttachments
{

    private string fileNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class SetVariables
{

    private SetVariablesSetVariable[] setVariableField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SetVariable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SetVariablesSetVariable[] SetVariable
    {
        get
        {
            return this.setVariableField;
        }
        set
        {
            this.setVariableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SetVariablesSetVariable
{

    private SetVariablesSetVariableResultSet[] resultSetField;

    private string sQLStatementField;

    private string targetConnectionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResultSet", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SetVariablesSetVariableResultSet[] ResultSet
    {
        get
        {
            return this.resultSetField;
        }
        set
        {
            this.resultSetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SQLStatement
    {
        get
        {
            return this.sQLStatementField;
        }
        set
        {
            this.sQLStatementField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetConnection
    {
        get
        {
            return this.targetConnectionField;
        }
        set
        {
            this.targetConnectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SetVariablesSetVariableResultSet
{

    private string variableNameField;

    private string orderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VariableName
    {
        get
        {
            return this.variableNameField;
        }
        set
        {
            this.variableNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class CHEFMetaData
{

    private CHEFMetaDataProcess processField;

    private string applicationNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Process", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcess Process
    {
        get
        {
            return this.processField;
        }
        set
        {
            this.processField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ApplicationName
    {
        get
        {
            return this.applicationNameField;
        }
        set
        {
            this.applicationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcess
{

    private CHEFMetaDataProcessConnectionSet[] connectionSetField;

    private SendMailTask[] sendMailTaskField;

    private CHEFMetaDataProcessVariablesVariable[] variablesField;

    private SetVariablesSetVariable[] setVariablesField;

    private CHEFMetaDataProcessStep[] stepField;

    private string defaultAllowTruncateField;

    private string verboseLoggingField;

    private string badRowsFolderLocationField;

    private string executeExistingPackageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ConnectionSet", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSet[] ConnectionSet
    {
        get
        {
            return this.connectionSetField;
        }
        set
        {
            this.connectionSetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SendMailTask")]
    public SendMailTask[] SendMailTask
    {
        get
        {
            return this.sendMailTaskField;
        }
        set
        {
            this.sendMailTaskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Variable", typeof(CHEFMetaDataProcessVariablesVariable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public CHEFMetaDataProcessVariablesVariable[] Variables
    {
        get
        {
            return this.variablesField;
        }
        set
        {
            this.variablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SetVariable", typeof(SetVariablesSetVariable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public SetVariablesSetVariable[] SetVariables
    {
        get
        {
            return this.setVariablesField;
        }
        set
        {
            this.setVariablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Step", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStep[] Step
    {
        get
        {
            return this.stepField;
        }
        set
        {
            this.stepField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefaultAllowTruncate
    {
        get
        {
            return this.defaultAllowTruncateField;
        }
        set
        {
            this.defaultAllowTruncateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VerboseLogging
    {
        get
        {
            return this.verboseLoggingField;
        }
        set
        {
            this.verboseLoggingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BadRowsFolderLocation
    {
        get
        {
            return this.badRowsFolderLocationField;
        }
        set
        {
            this.badRowsFolderLocationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ExecuteExistingPackage
    {
        get
        {
            return this.executeExistingPackageField;
        }
        set
        {
            this.executeExistingPackageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable, XmlRoot("ConnectionSet")]
public partial class CHEFMetaDataProcessConnectionSet
{

    private CHEFMetaDataProcessConnectionSetSQLConnection[] sQLConnectionField;

    private CHEFMetaDataProcessConnectionSetFileConnection[] fileConnectionField;

    private CHEFMetaDataProcessConnectionSetFlatFileConnection[] flatFileConnectionField;
    private CHEFMetaDataProcessConnectionSetTableStorageConnection[] tableStorageConnectionField;
    private CHEFMetaDataProcessConnectionSetSharePointListConnection[] sharePointListConnectionField;

    private CHEFMetaDataProcessConnectionSetSMTPConnection[] sMTPConnectionField;
    //private CHEFMetaDataProcessConnectionSetSMTPConnection[] tableStorageConnection;
    

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SQLConnection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSetSQLConnection[] SQLConnection
    {
        get
        {
            return this.sQLConnectionField;
        }
        set
        {
            this.sQLConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileConnection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSetFileConnection[] FileConnection
    {
        get
        {
            return this.fileConnectionField;
        }
        set
        {
            this.fileConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlatFileConnection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSetFlatFileConnection[] FlatFileConnection
    {
        get
        {
            return this.flatFileConnectionField;
        }
        set
        {
            this.flatFileConnectionField = value;
        }
    }
    

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SharePointListConnection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSetSharePointListConnection[] SharePointListConnection
    {
        get
        {
            return this.sharePointListConnectionField;
        }
        set
        {
            this.sharePointListConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TableStorageConnection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSetTableStorageConnection[] TableStorageConnection
    {
        get
        {
            return this.tableStorageConnectionField;
        }
        set
        {
            this.tableStorageConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SMTPConnection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessConnectionSetSMTPConnection[] SMTPConnection
    {
        get
        {
            return this.sMTPConnectionField;
        }
        set
        {
            this.sMTPConnectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessConnectionSetSQLConnection
{

    private string keyField;
    private string serverNameField;
    private string databaseNameField;
    private string userID;
    private string encryptedPassword;
    private string encrypt;
    private string trustedConnection;
     /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServerName
    {
        get
        {
            return this.serverNameField;
        }
        set
        {
            this.serverNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DatabaseName
    {
        get
        {
            return this.databaseNameField;
        }
        set
        {
            this.databaseNameField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserID
    {
        get
        {
            return this.userID;
        }
        set
        {
            this.userID = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EncryptedPassword
    {
        get
        {
            return this.encryptedPassword;
        }
        set
        {
            this.encryptedPassword = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Encrypt
    {
        get
        {
            return this.encrypt;
        }
        set
        {
            this.encrypt = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TrustedConnection
    {
        get
        {
            return this.trustedConnection;
        }
        set
        {
            this.trustedConnection = value;
        }
    }   
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessConnectionSetFileConnection
{

    private string keyField;

    private string fileNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessConnectionSetSharePointListConnection
{

    private string keyField;
    private string siteURLField;
    private string userIDField;
    private string encryptedPasswordField;
    private string useWindowsAuthenticationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SiteURL
    {
        get
        {
            return this.siteURLField;
        }
        set
        {
            this.siteURLField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserID
    {
        get
        {
            return this.userIDField;
        }
        set
        {
            this.userIDField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UseWindowsAuthentication
    {
        get
        {
            return this.useWindowsAuthenticationField;
        }
        set
        {
            this.useWindowsAuthenticationField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EncryptedPassword
    {
        get
        {
            return this.encryptedPasswordField;
        }
        set
        {
            this.encryptedPasswordField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessConnectionSetTableStorageConnection
{

    private string keyField;

    private string defaultEndpointsProtocolField;
    private string accountNameField;
    private string encryptedAccountKeyField;
    private string useDevelopmentStorageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefaultEndpointsProtocol
    {
        get
        {
            return this.defaultEndpointsProtocolField;
        }
        set
        {
            this.defaultEndpointsProtocolField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AccountName
    {
        get
        {
            return this.accountNameField;
        }
        set
        {
            this.accountNameField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EncryptedAccountKey
    {
        get
        {
            return this.encryptedAccountKeyField;
        }
        set
        {
            this.encryptedAccountKeyField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UseDevelopmentStorage
    {
        get
        {
            return this.useDevelopmentStorageField;
        }
        set
        {
            this.useDevelopmentStorageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessConnectionSetFlatFileConnection
{

    private string keyField;

    private string fileNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessConnectionSetSMTPConnection
{

    private string keyField;

    private string smtpServerField;

    private string useWindowsAuthenticationField;

    private string enableSslField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SmtpServer
    {
        get
        {
            return this.smtpServerField;
        }
        set
        {
            this.smtpServerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UseWindowsAuthentication
    {
        get
        {
            return this.useWindowsAuthenticationField;
        }
        set
        {
            this.useWindowsAuthenticationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EnableSsl
    {
        get
        {
            return this.enableSslField;
        }
        set
        {
            this.enableSslField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable, XmlRoot("Variable")]
public partial class CHEFMetaDataProcessVariablesVariable
{

    private string nameField;

    private string dataTypeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessStep
{

    private SendMailTask[] sendMailTaskField;

    private SetVariablesSetVariable[] setVariablesField;

    private CHEFMetaDataProcessStepSQLTaskSet[] sQLTaskSetField;

    private CHEFMetaDataProcessStepDataFlowSet[] dataFlowSetField;

    private CHEFMetaDataProcessStepTableStorageSet[] tableStorageSetField;

    
    private CHEFMetaDataProcessStepPackageExecution[] packageExecutionField;

    private string idField;

    private string nameField;

    private string typeIDField;

    private string typeNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SendMailTask")]
    public SendMailTask[] SendMailTask
    {
        get
        {
            return this.sendMailTaskField;
        }
        set
        {
            this.sendMailTaskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SetVariable", typeof(SetVariablesSetVariable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public SetVariablesSetVariable[] SetVariables
    {
        get
        {
            return this.setVariablesField;
        }
        set
        {
            this.setVariablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SQLTaskSet", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepSQLTaskSet[] SQLTaskSet
    {
        get
        {
            return this.sQLTaskSetField;
        }
        set
        {
            this.sQLTaskSetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataFlowSet", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepDataFlowSet[] DataFlowSet
    {
        get
        {
            return this.dataFlowSetField;
        }
        set
        {
            this.dataFlowSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TableStorageSet", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepTableStorageSet[] TableStorageSet
    {
        get
        {
            return this.tableStorageSetField;
        }
        set
        {
            this.tableStorageSetField = value;
        }
    }

    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackageExecution", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepPackageExecution[] PackageExecution
    {
        get
        {
            return this.packageExecutionField;
        }
        set
        {
            this.packageExecutionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeID
    {
        get
        {
            return this.typeIDField;
        }
        set
        {
            this.typeIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName
    {
        get
        {
            return this.typeNameField;
        }
        set
        {
            this.typeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable, XmlRoot("SQLTaskSet")]
public partial class CHEFMetaDataProcessStepSQLTaskSet
{

    private SetVariablesSetVariable[] setVariablesField;

    private CHEFMetaDataProcessStepSQLTaskSetSQLTask[] sQLTaskField;

    private SendMailTask[] sendMailTaskField;

    private string nameField;

    private string targetConnectionField;

    private string runParallelField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SetVariable", typeof(SetVariablesSetVariable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public SetVariablesSetVariable[] SetVariables
    {
        get
        {
            return this.setVariablesField;
        }
        set
        {
            this.setVariablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SQLTask", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepSQLTaskSetSQLTask[] SQLTask
    {
        get
        {
            return this.sQLTaskField;
        }
        set
        {
            this.sQLTaskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SendMailTask")]
    public SendMailTask[] SendMailTask
    {
        get
        {
            return this.sendMailTaskField;
        }
        set
        {
            this.sendMailTaskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetConnection
    {
        get
        {
            return this.targetConnectionField;
        }
        set
        {
            this.targetConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RunParallel
    {
        get
        {
            return this.runParallelField;
        }
        set
        {
            this.runParallelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessStepSQLTaskSetSQLTask
{

    private string nameField;

    private string sQLStatementField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SQLStatement
    {
        get
        {
            return this.sQLStatementField;
        }
        set
        {
            this.sQLStatementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable, XmlRoot("DataFlowSet")]
public partial class CHEFMetaDataProcessStepDataFlowSet
{

    private SetVariablesSetVariable[] setVariablesField;

    private CHEFMetaDataProcessStepDataFlowSetDataFlow[] dataFlowField;

    private SendMailTask[] sendMailTaskField;

    private string nameField;

    private string sourceConnectionField;

    private string targetConnectionField;

    private string sourceTypeField;

    private string targetTypeField;

    private string pickColumnsFromTargetField;

    private string columnDelimeterField;

    private string rowDelimeterField;

    private string isColumnNamesInFirstDataRowField;

    private string runParallelField;

    private string truncateOrDeleteBeforeInsertField;

    private string deleteFilterClauseField;

    private string abortFlatFileLoadPostErrorField;

    private string allowFlatFileTruncateField;

    private string uniCode;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SetVariable", typeof(SetVariablesSetVariable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public SetVariablesSetVariable[] SetVariables
    {
        get
        {
            return this.setVariablesField;
        }
        set
        {
            this.setVariablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataFlow", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepDataFlowSetDataFlow[] DataFlow
    {
        get
        {
            return this.dataFlowField;
        }
        set
        {
            this.dataFlowField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SendMailTask")]
    public SendMailTask[] SendMailTask
    {
        get
        {
            return this.sendMailTaskField;
        }
        set
        {
            this.sendMailTaskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceConnection
    {
        get
        {
            return this.sourceConnectionField;
        }
        set
        {
            this.sourceConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetConnection
    {
        get
        {
            return this.targetConnectionField;
        }
        set
        {
            this.targetConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceType
    {
        get
        {
            return this.sourceTypeField;
        }
        set
        {
            this.sourceTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetType
    {
        get
        {
            return this.targetTypeField;
        }
        set
        {
            this.targetTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PickColumnsFromTarget
    {
        get
        {
            return this.pickColumnsFromTargetField;
        }
        set
        {
            this.pickColumnsFromTargetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColumnDelimeter
    {
        get
        {
            return this.columnDelimeterField;
        }
        set
        {
            this.columnDelimeterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RowDelimeter
    {
        get
        {
            return this.rowDelimeterField;
        }
        set
        {
            this.rowDelimeterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsColumnNamesInFirstDataRow
    {
        get
        {
            return this.isColumnNamesInFirstDataRowField;
        }
        set
        {
            this.isColumnNamesInFirstDataRowField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RunParallel
    {
        get
        {
            return this.runParallelField;
        }
        set
        {
            this.runParallelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TruncateOrDeleteBeforeInsert
    {
        get
        {
            return this.truncateOrDeleteBeforeInsertField;
        }
        set
        {
            this.truncateOrDeleteBeforeInsertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeleteFilterClause
    {
        get
        {
            return this.deleteFilterClauseField;
        }
        set
        {
            this.deleteFilterClauseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AbortFlatFileLoadPostError
    {
        get
        {
            return this.abortFlatFileLoadPostErrorField;
        }
        set
        {
            this.abortFlatFileLoadPostErrorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AllowFlatFileTruncate
    {
        get
        {
            return this.allowFlatFileTruncateField;
        }
        set
        {
            this.allowFlatFileTruncateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniCode
    {
        get
        {
            return this.uniCode;
        }
        set
        {
            this.uniCode = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable, XmlRoot("TableStorageSet")]
public partial class CHEFMetaDataProcessStepTableStorageSet
{

    private SetVariablesSetVariable[] setVariablesField;

    private CHEFMetaDataProcessStepTableStorageSetTableStorage[] tableStorageField;

    private SendMailTask[] sendMailTaskField;

    private string nameField;

    private string sourceConnectionField;

    private string targetConnectionField;

    private string sourceTypeField;

    private string targetTypeField;

    private string runParallelField;

    private string truncateOrDeleteBeforeInsertField;

    private string deleteFilterClauseField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SetVariable", typeof(SetVariablesSetVariable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public SetVariablesSetVariable[] SetVariables
    {
        get
        {
            return this.setVariablesField;
        }
        set
        {
            this.setVariablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TableStorage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CHEFMetaDataProcessStepTableStorageSetTableStorage[] TableStorage
    {
        get
        {
            return this.tableStorageField;
        }
        set
        {
            this.tableStorageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SendMailTask")]
    public SendMailTask[] SendMailTask
    {
        get
        {
            return this.sendMailTaskField;
        }
        set
        {
            this.sendMailTaskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceConnection
    {
        get
        {
            return this.sourceConnectionField;
        }
        set
        {
            this.sourceConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetConnection
    {
        get
        {
            return this.targetConnectionField;
        }
        set
        {
            this.targetConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceType
    {
        get
        {
            return this.sourceTypeField;
        }
        set
        {
            this.sourceTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetType
    {
        get
        {
            return this.targetTypeField;
        }
        set
        {
            this.targetTypeField = value;
        }
    }

  
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RunParallel
    {
        get
        {
            return this.runParallelField;
        }
        set
        {
            this.runParallelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TruncateOrDeleteBeforeInsert
    {
        get
        {
            return this.truncateOrDeleteBeforeInsertField;
        }
        set
        {
            this.truncateOrDeleteBeforeInsertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeleteFilterClause
    {
        get
        {
            return this.deleteFilterClauseField;
        }
        set
        {
            this.deleteFilterClauseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessStepDataFlowSetDataFlow
{

    private CHEFMetaDataProcessStepDataFlowSetDataFlowColumnMappingMapping[] columnMappingField;

    private string nameField;

    private string sourceNameField;

    private string targetNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Mapping", typeof(CHEFMetaDataProcessStepDataFlowSetDataFlowColumnMappingMapping), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public CHEFMetaDataProcessStepDataFlowSetDataFlowColumnMappingMapping[] ColumnMapping
    {
        get
        {
            return this.columnMappingField;
        }
        set
        {
            this.columnMappingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceName
    {
        get
        {
            return this.sourceNameField;
        }
        set
        {
            this.sourceNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetName
    {
        get
        {
            return this.targetNameField;
        }
        set
        {
            this.targetNameField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessStepTableStorageSetTableStorage
{

    private string tableNameField;

    private string sourceNameField;

    private string targetNameField;

    private string partitionKeyField;

    private string rowKeyField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TableName
    {
        get
        {
            return this.tableNameField;
        }
        set
        {
            this.tableNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceName
    {
        get
        {
            return this.sourceNameField;
        }
        set
        {
            this.sourceNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetName
    {
        get
        {
            return this.targetNameField;
        }
        set
        {
            this.targetNameField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PartitionKey
    {
        get
        {
            return this.partitionKeyField;
        }
        set
        {
            this.partitionKeyField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RowKey
    {
        get
        {
            return this.rowKeyField;
        }
        set
        {
            this.rowKeyField = value;
        }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CHEFMetaDataProcessStepDataFlowSetDataFlowColumnMappingMapping
{

    private string sourceColumnField;

    private string targetColumnField;

    private string sourceTypeField;

    private string targetTypeField;

    private string sourceLengthField;

    private string targetLengthField;

    private string allowTruncateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceColumn
    {
        get
        {
            return this.sourceColumnField;
        }
        set
        {
            this.sourceColumnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetColumn
    {
        get
        {
            return this.targetColumnField;
        }
        set
        {
            this.targetColumnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceType
    {
        get
        {
            return this.sourceTypeField;
        }
        set
        {
            this.sourceTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetType
    {
        get
        {
            return this.targetTypeField;
        }
        set
        {
            this.targetTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceLength
    {
        get
        {
            return this.sourceLengthField;
        }
        set
        {
            this.sourceLengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetLength
    {
        get
        {
            return this.targetLengthField;
        }
        set
        {
            this.targetLengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AllowTruncate
    {
        get
        {
            return this.allowTruncateField;
        }
        set
        {
            this.allowTruncateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[Serializable, XmlRoot("PackageExecution")]
public partial class CHEFMetaDataProcessStepPackageExecution
{

    private string nameField;

    private string connectionField;

    private string packageNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Connection
    {
        get
        {
            return this.connectionField;
        }
        set
        {
            this.connectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageName
    {
        get
        {
            return this.packageNameField;
        }
        set
        {
            this.packageNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CHEFMetaData", typeof(CHEFMetaData))]
    [System.Xml.Serialization.XmlElementAttribute("SendMailTask", typeof(SendMailTask))]
    [System.Xml.Serialization.XmlElementAttribute("SetVariables", typeof(SetVariables))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
